import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" px-14">
        <ThemeProvider enableSystem={true} attribute="class">
          <div>
            <Navbar />
          </div>
          <div className="mt-8">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
